function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, YData4, XData4, YData5, XData5, YData6, XData6, YData7)
%CREATEFIGURE(XDATA1, YDATA1, XDATA2, YDATA2, XDATA3, YDATA3, YDATA4, XDATA4, YDATA5, XDATA5, YDATA6, XDATA6, YDATA7)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  XDATA4:  line xdata
%  YDATA5:  line ydata
%  XDATA5:  line xdata
%  YDATA6:  line ydata
%  XDATA6:  line xdata
%  YDATA7:  line ydata

%  Auto-generated by MATLAB on 09-Jun-2018 22:36:26

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.143123359580052 0.737027412079008 0.761876640419948 0.140891608636623]);
hold(axes1,'on');

% Create line
line(XData1,YData1,'Visible','off','Parent',axes1);

% Create hggroup
hggroup1 = hggroup('Parent',axes1,'DisplayName','Gz');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Magnitude (dB)','HitTest','off','FontSize',7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-50 50]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',8,'XColor',[0.4 0.4 0.4],'XGrid','on','XMinorTick',...
    'on','XScale','log','XTickLabel','','YColor',[0.4 0.4 0.4],'YGrid','on');
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.143123359580052 0.583837209302326 0.761876640419948 0.124941615206061]);
hold(axes2,'on');

% Create line
line(XData3,YData3,'Visible','off','Parent',axes2);

% Create hggroup
hggroup2 = hggroup('Parent',axes2,'DisplayName','Gz');

% Create line
line(XData2,YData4,'Parent',hggroup2,'Color',[0 0.447 0.741]);

% Create ylabel
ylabel('Phase (deg)','HitTest','off','FontSize',7);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-181.8 1.8]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',8,'XColor',[0.4 0.4 0.4],'XGrid','on','XMinorTick',...
    'on','XScale','log','YColor',[0.4 0.4 0.4],'YGrid','on','YTick',...
    [-180 -90 0]);
% Create xlabel
xlabel('Frequency  (rad/s)','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'Visible','on');

% Create title
title('Bode Diagram','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.143123359580052 0.11 0.761876640419948 0.294081811413305]);

% Create line
line(XData4,YData5,'Visible','off','Parent',axes3);

% Create hggroup
hggroup3 = hggroup('Parent',axes3,'DisplayName','Gz');

% Create line
line(XData5,YData6,'Parent',hggroup3,'Color',[0 0.447 0.741]);

% Create line
line(XData6,YData7,'Parent',hggroup3,'Color',[0 0.447 0.741]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[-10 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[-30 30]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',8,'XColor',[0 0 0],'YColor',[0 0 0]);
% Create ylabel
ylabel('Imaginary Axis','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',8,...
    'Visible','on');

% Create xlabel
xlabel('Real Axis','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',8,...
    'Visible','on');

% Create title
title('Nyquist Diagram','HitTest','off','Units','pixels',...
    'HorizontalAlignment','center',...
    'FontSize',8);

